# Generated by Django 4.1.3 on 2022-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_send', models.CharField(max_length=200)),
                ('messages', models.CharField(max_length=1000)),
            ],
        ),
    ]
