# Generated by Django 4.1.3 on 2022-11-20 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 16, 31, 19, 367345)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='messages',
            field=models.TextField(max_length=1000),
        ),
    ]
