# Generated by Django 4.1.3 on 2022-11-21 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_feedback_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800)),
                ('op1', models.CharField(max_length=500, null=True)),
                ('op2', models.CharField(max_length=500, null=True)),
                ('op3', models.CharField(max_length=500, null=True)),
                ('op4', models.CharField(max_length=500, null=True)),
                ('ans', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 10, 55, 12, 520930)),
        ),
    ]
