# Generated by Django 4.1.3 on 2022-11-21 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_feedback_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 15, 53, 21, 669533)),
        ),
    ]
